use DemoDB; 

drop table Dept; 
drop table Employee;
CREATE TABLE `Dept`(
    `DeptID` INT PRIMARY KEY AUTO_INCREMENT,
    `Name` VARCHAR(50) not null,
    `Location` VARCHAR(50) NOT NULL
); 
alter table `Dept` auto_increment = 101; 
 
CREATE TABLE `Employee`(
    `EmpID` INT PRIMARY KEY AUTO_INCREMENT,
    `FirstName` VARCHAR(50),
    LastName VARCHAR(50),
    `DeptID` INT REFERENCES Dept, 
    Salary NUMERIC(10,2) NOT NULL CHECK (Salary > 0)
); 
 
-- sample records
-- Here DeptID is autogenerated you can see it is selected
-- for auto_increment.
INSERT INTO `Dept`(`Name`,`Location`)
VALUES('Inventory', 'Deer Creek');
INSERT INTO `Dept`(`Name`,`Location`)
VALUES('Sales', 'Great Woods');
INSERT INTO `Dept`(`Name`,`Location`)
VALUES('HR', 'Great Woods');
 
-- Below insert command is very useful in SQL in Project
-- When you are inserting master data and if you do not know 
-- the generated ID then the query could be used to get the 
-- generated ID and given as input to the insert.
-- Here the output of the select command is given as input for 
-- DeptID column value.
-- NOTE - You need to make sure that it only retrieves one value
-- if it retrieves multiple values then it lead to failure.
INSERT INTO `Employee`(`FirstName`, `LastName`, `DeptID`, `Salary`)
VALUES('Trey','Anastasio', (SELECT `DeptID` FROM `Dept` WHERE `Name`='Inventory'), 11000);

INSERT INTO `Employee`(`FirstName`, `LastName`, `DeptID`, `Salary`)
VALUES('Page','McConnell', (SELECT `DeptID` FROM `Dept` WHERE `Name`='Sales'), 12000);
 
INSERT INTO `Employee`(`FirstName`, `LastName`, `DeptID`, `Salary`)
VALUES('Jon','Fishman', (SELECT `DeptID` FROM `Dept` WHERE `Name`='HR'), 21000);
 
INSERT INTO `Employee`(`FirstName`, `LastName`, `DeptID`, `Salary`)
VALUES('Mike','Gordon', 103, 22000);

-- basic queries
SELECT * FROM `Dept`;
SELECT * FROM `Employee`;

-- only displays employees whose DeptID corresponds to a DeptID in Dept with same number and named HR
-- these are correlated subqueries
select * from Employee as e
where
exists (select * from Dept where DeptID = e.DeptID and Name = 'HR'); 

select e.* from Employee as e
inner join Dept as d on (e.DeptID = d.DeptID and d.Name = 'HR'); 